author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Client-Pastebot
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::TokeParser: 0
  LWP::UserAgent: 0
  POE: 0.38
  URI: 0
version: 0.03
