---
abstract: 'Interact with Bot::Pastebot web services from POE.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Date: 0
  HTTP::Response: 0
  POE::Filter::HTTP::Parser: 1.02
  Test::More: 0.47
  Test::POE::Server::TCP: 1.06
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-Pastebot
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Client::Pastebot:
    file: lib/POE/Component/Client/Pastebot.pm
    version: 1.14
requires:
  HTML::TokeParser: 0
  HTTP::Request::Common: 0
  POE: 1.294
  POE::Component::Client::HTTP: 0.88
  URI: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-client-pastebot/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-client-pastebot.git
version: 1.14
