---
abstract: 'Interact with Bot::Pastebot web services from POE.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.86'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-Pastebot
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  HTML::TokeParser: 0
  POE: 1.005
  POE::Component::Client::HTTP: 0.88
  URI: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-client-pastebot/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-client-pastebot.git
version: 1.10
